using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Educational_Center_Management_System.Models
{
    public record class Score
    {
        public int Id { get; init; } // Auto-generated by DB
        public int StudentId { get; init; }     
        public int ClassId { get; init; }
        public double Number { get; init; }
    }
}
