using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Educational_Center_Management_System.Models
{
    public record class Student
    {
        public int Id { get; init; } // Auto-generated by DB
        public string Name { get; init; }
        public string LastName { get; init; }
        public string Fathername { get; init; }
        public DateOnly BirthDate { get; init; }
        public byte[]? Photo { get; init; }
        public string PhoneNumber { get; init; }
        public DateOnly JoinDate { get; init; }
        public int State { get; init; }
        public string Password { get; init; }

        public static implicit operator Task<object>(Student? v)
        {
            throw new NotImplementedException();
        }
    }
}
