using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Educational_Center_Management_System.Models
{
    public record class Student
    {
        public int Id { get; set; } // Auto-generated by DB
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Fathername { get; set; }
        public DateOnly BirthDate { get; set; }
        public byte[]? Photo { get; set; }
        public string PhoneNumber { get; set; }
        public DateOnly JoinDate { get; set; }
        public int State { get; set; }
        public string Password { get; set; }
    }
}
